# 3. 데이터 분석 기초와 시각화

- 목표: 넘파이, 판다스, 기술통계, 시각화, 데이터 정리의 핵심만 압축해서 다시 훑습니다.
- 흐름: 데이터 분석 도구를 익힌 뒤 머신러닝에서 쓰는 수학과 모델 학습 흐름으로 이어집니다.


# 데이터 사이언스 Toolkit

### 수업 목표
- 데이터 과학의 핵심 라이브러리 생태계(Numpy, Pandas, Matplotlib)를 **큰 그림**에서 이해한다.
- Numpy로 수치 데이터를 **효율적으로** 생성, 조작, 연산할 수 있다.
- 선형대수학의 기초 개념(벡터, 행렬, 연산, 전치/역행렬)을 **넘파이 코드로 구현**할 수 있다.

### 왜 Numpy, Pandas, Matplotlib 인가
- Numpy: 파이썬에서 **고성능 수치 연산**을 담당하는 **배열 엔진**. ML/DL의 전처리와 수치 연산의 기반.
- Pandas: **표 형식 데이터프레임**으로 정리·가공·집계에 최적. 실무 데이터 핸들링의 표준.
- Matplotlib: 분석 결과를 **시각화**하여 패턴을 발견하고 의사결정을 돕는다.

![image.png](image/numpy.png)
### Numpy의 특징

- **빠른 배열 연산**  
  - 파이썬의 기본 리스트보다 훨씬 빠른 속도로 벡터와 행렬 연산을 수행한다.  
  - 내부적으로 C 언어로 구현되어 있어 반복문을 직접 작성하지 않아도 된다.  

- **다양한 수학 함수 제공**  
  - 합계, 평균, 표준편차 같은 기본 통계부터, 선형대수(행렬 곱, 역행렬 등), 푸리에 변환까지 지원한다.  

- **브로드캐스팅(Broadcasting)**  
  - 크기가 다른 배열끼리도 규칙에 따라 자동으로 맞춰 연산할 수 있다.  
  - 예: 행렬 전체에 상수 더하기, 벡터를 행렬 각 행에 더하기. 
  
  - ![image-2.png](image/Broadcasting.png)  
  출처 : http://www.astroml.org/book_figures/appendix/fig_broadcast_visual.html


- **머신러닝/딥러닝의 기반**  
  - 텐서플로우(TensorFlow), 파이토치(PyTorch) 같은 딥러닝 프레임워크도 내부 연산을 Numpy와 유사한 구조로 수행한다.  
  - 즉, **Numpy 배열을 자유자재로 다룰 수 있어야 ML/DL의 연산 원리를 이해할 수 있다.**

## 1. 선형대수학 기초

### 1.1 벡터(Vector)
- 벡터는 여러 숫자를 **순서대로 나열한 것**  
- 흔히 화살표(방향과 크기) 또는 좌표처럼 생각할 수 있다.  
- 벡터는 "차원(dimension)"의 개수에 따라 구분된다.  


#### 1차원 벡터 (1D Vector)
- 숫자 1개만 가지는 벡터
- 단순히 **실수축 위의 한 점**  
- $\vec{v} = \begin{bmatrix} 3 \end{bmatrix}$ 
- ---●--------→ x


#### 2차원 벡터 (2D Vector)
- 숫자 2개 (x, y)  
- 평면 위의 점 혹은 "화살표"  
- $\vec{v} = \begin{bmatrix} 2 \\ 3 \end{bmatrix}$
```yaml
y ↑
|
3 | ● (2,3)
|
|—2—————→ x
```

#### 3차원 벡터 (3D Vector)
- 숫자 3개 (x, y, z)  
- 공간(입체) 속의 한 점  
- $\vec{v} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$
- 
- 좌표 (1,2,3) 은 "x축으로 1, y축으로 2, z축으로 3 이동한 점"을 의미한다.  


####  벡터의 연산
- 덧셈: 
$$
\begin{bmatrix} 1 \\ 2 \end{bmatrix} +
\begin{bmatrix} 3 \\ 4 \end{bmatrix} =
\begin{bmatrix} 4 \\ 6 \end{bmatrix}
$$

- 스칼라 곱: 
$$
2 \times \begin{bmatrix} 1 \\ 2 \end{bmatrix} =
\begin{bmatrix} 2 \\ 4 \end{bmatrix}
$$


### 1.2 행렬(Matrix)

- 행렬은 숫자를 **직사각형 모양**으로 배열한 것  
- 여러 벡터를 모아 만든 "데이터 표"  

예:  
$$
A =
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{bmatrix}
$$

- 크기: 3행 2열 (3×2 행렬)
#### 💡 행렬의 의미
- **데이터 표**: 행 = 샘플, 열 = 변수  
- **벡터의 집합**: 여러 벡터(2개 이상)의 모음
- **선형 변환**: 벡터를 입력하면, 특정 규칙(행렬 곱)에 따라 새로운 벡터로 바꿔주는 과정
→ 마치 벡터를 "회전, 확대/축소, 반사"시키는 것처럼 생각할 수 있다.



### 1.3 행렬 연산

1. **덧셈/뺄셈**  
   - 같은 크기의 행렬끼리만 가능  
   $$
   \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} +
   \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix} =
   \begin{bmatrix} 6 & 8 \\ 10 & 12 \end{bmatrix}
   $$

2. **스칼라 곱**  
   - 모든 원소에 같은 수 곱하기  
   $$
   2 \times \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} =
   \begin{bmatrix} 2 & 4 \\ 6 & 8 \end{bmatrix}
   $$

3. **행렬 곱**  
   - "앞 행렬의 행 × 뒤 행렬의 열"  
   - (m×n) × (n×p) = (m×p)  
   $$
   \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
   \times
   \begin{bmatrix} 5 \\ 6 \end{bmatrix}
   =
   \begin{bmatrix} 17 \\ 39 \end{bmatrix}
   $$


### 1.4 전치/단위/역행렬

- **전치행렬 (Transpose)**: 행과 열을 뒤바꾼 행렬  
  $$
  \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}^T =
  \begin{bmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{bmatrix}
  $$

- **단위행렬 (Identity)**: 대각선이 1, 나머지는 0  
  $$
  I = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}
  $$

- **역행렬 (Inverse)**: A와 곱했을 때 단위행렬이 되는 행렬  
  $$
  A \times A^{-1} = I
  $$


### 1.5 선형시스템 (Ax = b)

- 연립방정식을 행렬과 벡터로 표현할 수 있다.

예:  
$$
2x + y = 4 \\
x - y = 1
$$

- → 행렬 표현: 

    $$
    \begin{bmatrix}
    2 & 1 \\
    1 & -1
    \end{bmatrix}
    \begin{bmatrix}
    x \\
    y
    \end{bmatrix}
    =
    \begin{bmatrix}
    4 \\
    1
    \end{bmatrix}
    $$

👉 연립방정식을 간단히 \(Ax = b\) 꼴로 표현할 수 있다.



### 체크포인트
- **벡터**는 숫자의 나열이며, 1D/2D/3D로 구분된다.  
- **행렬**은 여러 벡터를 모아둔 2차원 구조다.  
- 행렬 곱은 "행 × 열" 규칙으로 계산한다.  
- 전치, 단위, 역행렬은 행렬의 기본 개념이다.  
- 연립방정식은 \(Ax = b\) 로 표현할 수 있다.


## 2. Numpy 기초

#### 배열이란?
- **배열(array)** 은 같은 종류의 데이터를 일정한 모양(행렬 형태)으로 모아놓은 것
- 파이썬 기본 리스트(list)와 달리, 배열은 **모든 원소가 같은 자료형**을 가지며 **고속 연산**이 가능
- 데이터 과학에서 다루는 데이터(표, 이미지, 시계열)는 대부분 "숫자들의 모음" → 배열로 표현하면 효율적

예시:
- 1차원 배열: `[1, 2, 3, 4]` (벡터)
- 2차원 배열: `[[1, 2], [3, 4]]` (행렬)
- 3차원 배열: 이미지(높이 × 너비 × 색상 채널)

#### 배열 생성 방법

- `np.array(리스트)` : 파이썬 리스트를 배열로 변환
- `np.arange(시작, 끝, 간격)` : 특정 범위의 정수를 순차적으로 생성
- `np.zeros(크기)` : 0으로 채운 배열 생성
- `np.ones(크기)` : 1로 채운 배열 생성
- `np.linspace(시작, 끝, 개수)` : 지정한 구간을 일정 간격으로 나눈 값 생성


#### 자료형 (dtype)

- 배열의 모든 원소는 **같은 자료형(dtype)** 을 가짐
- 기본적으로는 입력 데이터에 따라 자동 결정되지만, 직접 지정 가능
- 주요 자료형: int32, float64, bool, str
- `dtype` 로 자료형 지정 및 확인 가능

👉 여기서 `int32`의 **32**는 "32비트 정수"라는 뜻  
- **비트(bit)** = 컴퓨터가 정보를 저장하는 최소 단위 (0 또는 1)  
- **32비트 정수**는 32개의 0/1로 수를 표현 → 약 ±21억까지 표현 가능  
- **64비트 정수**는 더 많은 비트를 쓰기 때문에 훨씬 더 큰 수까지 표현 가능  
- 마찬가지로 `float32`, `float64`는 소수점 실수를 32비트 / 64비트로 저장  
  → 64비트는 더 정밀한 소수 계산 가능  

즉, 숫자가 커지거나 정밀도가 필요할수록 더 많은 비트를 사용하는 자료형을 선택한다.

In [ ]:
import numpy as np  # 배열과 수치 연산 라이브러리입니다.

a = np.array([1, 2, 3])                 # 기본 배열
b = np.arange(0, 10, 2)                 # 0,2,4,6,8
z = np.zeros((2, 3), dtype=np.float32)  # 2x3 영행렬
o = np.ones((3, 1))                     # 3x1 일행렬
l = np.linspace(0, 1, 5)                # 0~1 구간 5등분

print(a.dtype, z.shape, l)  # 문자열을 정수로 바꿉니다.

## 3. 인덱싱(Indexing)과 슬라이싱(Slicing)

#### 배열에서 값 꺼내기 (Indexing)
- 배열의 특정 위치에 접근할 때는 **인덱스(index)** 사용
- 파이썬과 Numpy는 **0부터 시작**
- 음수 인덱스는 뒤에서부터 세기


In [ ]:
arr = np.array([10, 20, 30, 40, 50])  # 넘파이 배열을 만듭니다.

print(arr[0])   # 첫 번째 원소 → 10
print(arr[-1])  # 마지막 원소 → 50

#### 배열의 일부 꺼내기 (Slicing)

- 시작:끝 형태로 잘라내기 (끝은 포함되지 않음)
- 시작:끝:간격 으로 일정 간격으로 추출 가능

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  # 넘파이 배열을 만듭니다.

print(arr[2:5])    # 인덱스 2~4 → [2 3 4]
print(arr[:4])     # 처음~3까지 → [0 1 2 3]
print(arr[5:])     # 5부터 끝까지 → [5 6 7 8 9]
print(arr[::2])    # 2칸씩 건너뛰기 → [0 2 4 6 8]

#### 2차원 배열에서 인덱싱/슬라이싱
- [행, 열] 형태로 접근
- 슬라이싱은 각각의 차원에 적용 가능

In [ ]:
mat = np.array([[1, 2, 3],  # 넘파이 배열을 만듭니다.
                [4, 5, 6],
                [7, 8, 9]])

print(mat[0, 0])     # (0행, 0열) → 1
print(mat[1, :])     # 1행 전체 → [4 5 6]
print(mat[:, 2])     # 모든 행의 2열 → [3 6 9]
print(mat[0:2, 1:3]) # 부분 배열(0~1행, 1~2열)

### 연습 문제

### 문제 1
1부터 10까지의 정수를 원소로 가지는 배열을 만들고,  
- 첫 번째 원소  
- 마지막 원소  
- 인덱스 3~6 구간 (즉, 4번째부터 7번째까지)  

를 각각 출력하세요.

<details>
<summary>정답 보기</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

arr = np.arange(1, 11)  # 실습에 사용할 배열을 만듭니다.

print(arr[0])  # 결과를 화면에 출력합니다.
print(arr[-1])  # 결과를 화면에 출력합니다.
print(arr[3:7])  # 결과를 화면에 출력합니다.

```
</details>


In [ ]:
# 여기에 문제 1 작성하세요


### 문제 2
다음 배열이 있을 때  
```python
arr = np.array([[10, 20, 30],  # 넘파이 배열을 만듭니다.
                [40, 50, 60],
                [70, 80, 90]])
```
- 2행 전체를 출력하세요.
- 1열(세로 방향)을 출력하세요.
- 부분 배열 [[20, 30], [50, 60]] 을 슬라이싱으로 꺼내보세요.

<details>
<summary>정답 보기</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

arr = np.array([[10, 20, 30],  # 실습에 사용할 배열을 만듭니다.
                [40, 50, 60],
                [70, 80, 90]])

print(arr[1, :])  # 결과를 화면에 출력합니다.
print(arr[:, 0])  # 결과를 화면에 출력합니다.
print(arr[:2, 1:])  # 결과를 화면에 출력합니다.

```
</details>


In [ ]:
arr = np.array([[10, 20, 30],  # 넘파이 배열을 만듭니다.
                [40, 50, 60],
                [70, 80, 90]])


## 4. 불린 인덱싱
**불린 인덱싱이란?**
- 배열에서 **조건을 만족하는 원소만** 골라내는 방법
- 조건식을 쓰면 True/False 로 된 "마스크(mask)" 배열이 만들어지고,
  이 마스크를 원래 배열에 적용하면 True인 원소만 선택됨


In [ ]:
y = np.array([3, 6, 9, 12, 15])  # 넘파이 배열을 만듭니다.
mask = (y % 6 == 0)
print(mask)     # [False  True False  True False]
print(y[mask])  # [ 6 12] 

#### 여러 조건 결합
- `&` (and), `|` (or), `~` (not) 를 이용해 조건을 결합할 수 있음


In [ ]:
arr = np.array([10, 15, 20, 25, 30])  # 넘파이 배열을 만듭니다.

# 15 이상이고 30 미만인 원소만
print(arr[(arr >= 15) & (arr < 30)])   # [15 20 25]

In [ ]:
# 20이 아닌 원소만
print(arr[arr != 20]) # [10 15 25 30]

### 불린 인덱싱의 장점
- 반복문 없이 조건에 맞는 데이터를 빠르게 추출 가능
- 데이터 분석에서 "필터링"할 때 매우 유용

#### ✅ 체크포인트
- 불린 인덱싱은 **조건식 → True/False 배열 → True만 선택** 과정이다.
- 조건을 결합할 때는 `and/or` 대신 `&` 와 `|` 를 쓴다.
- `~` 는 조건을 반대로 뒤집는다.


### 연습 문제

### 문제 1
아래 배열이 있을 때,
- 15보다 큰 원소만 출력하세요.
- 10 이상 25 이하인 원소만 출력하세요.
```python
arr = np.array([5, 10, 15, 20, 25, 30])  # 넘파이 배열을 만듭니다.
```

<details>
<summary>정답 보기</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

arr = np.array([5, 10, 15, 20, 25, 30])  # 실습에 사용할 배열을 만듭니다.

print(arr[arr > 15])  # 결과를 화면에 출력합니다.
print(arr[(arr >= 10) & (arr <= 25)])  # 결과를 화면에 출력합니다.

```
</details>


In [ ]:
# 여기에 문제 1 작성하세요
arr = np.array([5, 10, 15, 20, 25, 30])  # 넘파이 배열을 만듭니다.


### 문제 2
다음 배열이 있을 때,
- 3의 배수이면서 2의 배수인 원소만 출력하세요.
- 10보다 작거나 15보다 큰 원소만 출력하세요.

```python
arr = np.array([3, 6, 9, 12, 15, 18])  # 넘파이 배열을 만듭니다.
```

<details>
<summary>정답 보기</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

arr = np.array([3, 6, 9, 12, 15, 18])  # 실습에 사용할 배열을 만듭니다.

print(arr[(arr % 3 == 0) & (arr % 2 == 0)])  # 결과를 화면에 출력합니다.
print(arr[(arr < 10) | (arr > 15)])  # 결과를 화면에 출력합니다.

```
</details>


In [ ]:
# 여기에 문제 2 작성하세요
arr = np.array([3, 6, 9, 12, 15, 18])  # 넘파이 배열을 만듭니다.


## 5. 기본 연산 (Arithmetic & Aggregation)

### 1) 스칼라 연산
- 배열과 숫자(스칼라)를 더하거나 빼면, 모든 원소에 연산이 적용됨
- 반복문을 쓰지 않아도 자동으로 전체 원소에 반영됨


In [ ]:
import numpy as np  # 배열과 수치 연산 라이브러리입니다.

arr = np.array([1, 2, 3, 4, 5])  # 넘파이 배열을 만듭니다.
print(arr + 10)   # [11 12 13 14 15]
print(arr * 2)    # [ 2  4  6  8 10]

### 2) 배열 간 연산
- 같은 크기의 배열끼리는 원소별로 연산이 수행됨
- (행렬 곱이 아니라, 원소별 곱이라는 점에 주의!)


In [ ]:
import numpy as np  # 배열과 수치 연산 라이브러리입니다.

a = np.array([1, 2, 3])  # 넘파이 배열을 만듭니다.
b = np.array([10, 20, 30])  # 넘파이 배열을 만듭니다.

print(a + b)   # [11 22 33]
print(a * b)   # [10 40 90]
print(a ** 2)  # [1 4 9]

### 3) 집계 함수 (Aggregation)
- 배열 전체의 합계, 평균, 최댓값 등을 한 번에 계산
- 자주 쓰이는 함수: `sum`, `mean`, `max`, `min`, `argmax`, `argmin`

In [ ]:
import numpy as np  # 배열과 수치 연산 라이브러리입니다.

x = np.array([5, 7, 3, 9])  # 넘파이 배열을 만듭니다.

print(x.sum())      # 24 (합계)
print(x.mean())     # 6.0 (평균)
print(x.max())      # 9 (최댓값)
print(x.min())      # 3 (최솟값)
print(x.argmax())   # 3 (최댓값의 위치)
print(x.argmin())   # 2 (최솟값의 위치)

### 4) 다차원 배열에서의 집계
- `axis` 옵션을 이용하면 행/열 방향으로 집계를 낼 수 있음
- `axis=0`: 세로 방향(열 단위)
- `axis=1`: 가로 방향(행 단위)

In [ ]:
mat = np.array([[1, 2, 3],  # 넘파이 배열을 만듭니다.
                [4, 5, 6]])

print(mat.sum())         # 21 (전체 합)
print(mat.sum(axis=0))   # [5 7 9] (열별 합)
print(mat.sum(axis=1))   # [6 15]  (행별 합)


### ✅ 체크포인트
- 스칼라 연산: 배열의 모든 원소에 동일하게 적용된다.
- 배열 간 연산: 같은 위치끼리 원소별 연산을 수행한다.
- 집계 함수: 전체/행/열 단위로 합계, 평균, 최댓값 등을 계산할 수 있다.


### 연습 문제

### 문제 1
배열 arr = np.array([2, 4, 6, 8, 10])에 대해:

1. 모든 원소를 제곱한 결과를 출력하세요.
2. 모든 원소의 평균을 출력하세요.

<details>
<summary>정답</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

import numpy as np  # 배열 계산을 위한 Numpy입니다.

arr = np.array([2, 4, 6, 8, 10])  # 실습에 사용할 배열을 만듭니다.
print(arr ** 2)     # [  4  16  36  64 100]
print(arr.mean())   # 6.0

```
</details>

In [ ]:
# 여기에 작성하세요
import numpy as np  # 배열과 수치 연산 라이브러리입니다.
arr = np.array([2, 4, 6, 8, 10])  # 넘파이 배열을 만듭니다.

### 문제 2

아래 2차원 배열에 대해 
- 전체 합계를 구하세요.
- 각 열의 최댓값을 구하세요.
- 각 행의 평균을 구하세요.
```python 
mat = np.array([[10, 20, 30],  # 넘파이 배열을 만듭니다.
                [40, 50, 60]])
```

<details>
<summary>정답</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

import numpy as np  # 배열 계산을 위한 Numpy입니다.

mat = np.array([[10, 20, 30],  # 2차원 배열을 준비합니다.
                [40, 50, 60]])

print(mat.sum())        # 210
print(mat.max(axis=0))  # [40 50 60]
print(mat.mean(axis=1)) # [20. 50.]

```

</details>

In [ ]:
# 여기에 작성하세요
import numpy as np  # 배열과 수치 연산 라이브러리입니다.

## 6. Numpy 심화

### 1) 배열 결합 (Concatenate, Stack)

#### 배열 합치기 (concatenate)
- 여러 배열을 하나로 이어 붙이는 기능
- `axis=0`: 행(세로)로 붙이기  
- `axis=1`: 열(가로)로 붙이기


In [ ]:
import numpy as np  # 배열과 수치 연산 라이브러리입니다.

a = np.array([[1, 2],  # 넘파이 배열을 만듭니다.
              [3, 4]])
b = np.array([[5, 6]])  # 넘파이 배열을 만듭니다.

print(np.concatenate([a, b], axis=0))  # 문자열을 정수로 바꿉니다.
# [[1 2]
#  [3 4]
#  [5 6]]

#### 배열 쌓기 (stack)
- 차원을 하나 늘려서 쌓음
- np.stack([a, b], axis=0) → 새로운 축 생성

In [ ]:
x = np.array([1, 2, 3])  # 넘파이 배열을 만듭니다.
y = np.array([4, 5, 6])  # 넘파이 배열을 만듭니다.

print(np.stack([x, y], axis=0))  # 문자열을 정수로 바꿉니다.
# [[1 2 3]
#  [4 5 6]]

### 2) 브로드캐스팅 (Broadcasting)
- 크기가 다른 배열끼리 연산할 때, 작은 배열을 자동으로 확장해 맞추는 기능
- 규칙: 뒤에서부터 차원을 비교 → 1 또는 같은 크기면 연산 가능

  <img src="image/Broadcasting.png">


In [ ]:
np.ones((3, 4))

In [ ]:
M = np.ones((3, 4))   # (3행 4열)
row = np.array([1, 2, 3, 4])   # (4,)

print(M + row)  # 문자열을 정수로 바꿉니다.
# 각 행에 row가 더해짐

In [ ]:
col = np.array([[10],  # 넘파이 배열을 만듭니다.
                [20],
                [30]])  # (3행 1열)

print(M + col)  # 문자열을 정수로 바꿉니다.
# 각 열에 col이 더해짐

## Numpy 추가 연습

배열 모양 변경, 브로드캐스팅, 마스킹, 행렬 연산을 직접 확인합니다. 필요한 문제부터 골라 풉니다.


### 문제 1. 배열 이어 붙이기
아래 두 배열을 이어 붙여 새로운 배열을 만들어보세요.

```python
a = np.array([[1, 2],  # 넘파이 배열을 만듭니다.
              [3, 4]])
b = np.array([[5, 6]])  # 넘파이 배열을 만듭니다.
```

- axis=0 방향으로 합치기
- axis=1 방향으로 합치기

<details>
<summary>정답</summary>

```python
# 풀이 흐름: 실습에 사용할 Numpy 배열을 준비합니다.
# 배열 연산으로 원하는 결과를 계산합니다.

a = np.array([[1, 2],  # 넘파이 배열을 만듭니다.
              [3, 4]])
b = np.array([[5, 6]])  # 모델이 학습할 절편입니다.

print(np.concatenate([a, b], axis=0))  # 결과를 화면에 출력합니다.
# [[1 2]
#  [3 4]
#  [5 6]]

print(np.concatenate([a, b.T], axis=1))  # 결과를 화면에 출력합니다.
# [[1 2 5]
#  [3 4 6]]

```
</details>

In [ ]:
### 여기에 작성하세요
a = np.array([[1, 2],  # 넘파이 배열을 만듭니다.
              [3, 4]])
b = np.array([[5, 6]])  # 넘파이 배열을 만듭니다.

### 문제 2. 브로드캐스팅

다음 배열이 있을 때, 브로드캐스팅을 이용해 계산하세요.

```python
M = np.array([[1, 2, 3],  # 넘파이 배열을 만듭니다.
              [4, 5, 6]])
v = np.array([10, 20, 30])  # 넘파이 배열을 만듭니다.
```

M + v 의 결과를 출력하세요.

<details> <summary>정답</summary>

```python
# 풀이 흐름: 실습에 사용할 Numpy 배열을 준비합니다.
# 배열 연산으로 원하는 결과를 계산합니다.

import numpy as np  # 배열 계산을 위한 Numpy입니다.

M = np.array([[1, 2, 3],  # 브로드캐스팅을 확인할 2차원 배열입니다.
              [4, 5, 6]])
v = np.array([10, 20, 30])  # 행마다 더할 1차원 배열입니다.

print(M + v)  # 결과를 화면에 출력합니다.
# [[11 22 33]
#  [14 25 36]]

```
</details>

In [ ]:
### 여기에 작성하세요
M = np.array([[1, 2, 3],  # 넘파이 배열을 만듭니다.
              [4, 5, 6]])
v = np.array([10, 20, 30])  # 넘파이 배열을 만듭니다.

### 문제 3. stack으로 배열 만들기

길이 3 벡터 x = [1, 2, 3], y = [4, 5, 6]를

- stack을 이용해 (2행 3열) 배열로 만들기
- stack을 이용해 (3행 2열) 배열로 만들기

<details><summary>정답</summary>

```python
# 풀이 흐름: 실습에 사용할 Numpy 배열을 준비합니다.
# 배열 연산으로 원하는 결과를 계산합니다.

import numpy as np  # 배열 계산을 위한 Numpy입니다.

x = np.array([1, 2, 3])  # 첫 번째 값 또는 배열을 준비합니다.
y = np.array([4, 5, 6])  # 정답 값 또는 두 번째 배열을 준비합니다.

print(np.stack([x, y], axis=0))  # 결과를 화면에 출력합니다.
# [[1 2 3]
#  [4 5 6]]

print(np.stack([x, y], axis=1))  # 결과를 화면에 출력합니다.
# [[1 4]
#  [2 5]
#  [3 6]]

```
</details> 

In [ ]:
### 여기에 작성하세요
x = np.array([1, 2, 3])  # 넘파이 배열을 만듭니다.
y = np.array([4, 5, 6])  # 넘파이 배열을 만듭니다.

### 문제 4. 불린 마스킹
아래 배열에서 짝수만 골라내는 코드를 작성하세요.

```python
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])  # 넘파이 배열을 만듭니다.
```

<details><summary>정답</summary>

```python
# 풀이 흐름: 실습에 사용할 Numpy 배열을 준비합니다.
# 배열 연산으로 원하는 결과를 계산합니다.

print(arr[arr % 2 == 0])  # 결과를 화면에 출력합니다.
# [ 2  4  6  8 10]

```
</details>

In [ ]:
### 여기에 작성하세요
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])  # 넘파이 배열을 만듭니다.

### 문제 5. 평균, 표준편차, 분산
아래 배열의 평균, 표준편차, 분산을 구하세요.

```python
arr = np.array([1, 2, 3, 4, 5])  # 넘파이 배열을 만듭니다.
```

<details><summary>정답</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

print(np.mean(arr))  # 3.0
print(np.std(arr))   # 1.4142135623730951
print(np.var(arr))   # 2.0

```
</details>

In [ ]:
### 여기에 작성하세요
arr = np.array([1, 2, 3, 4, 5])  # 넘파이 배열을 만듭니다.

### 문제 6. reshape
0부터 19까지의 정수로 이루어진 1차원 배열을 만들고, 이를 (4, 5) 모양으로 재구성하세요.

<details><summary>정답</summary>

```python
# 풀이 흐름: 실습에 사용할 Numpy 배열을 준비합니다.
# 배열 연산으로 원하는 결과를 계산합니다.

arr = np.arange(20)  # 실습에 사용할 배열을 만듭니다.
print(arr.reshape(4, 5))  # 결과를 화면에 출력합니다.
# [[ 0  1  2  3  4]
#  [ 5  6  7  8  9]
#  [10 11 12 13 14]
#  [15 16 17 18 19]]

```
</details>

In [ ]:
### 여기에 작성하세요

### 문제 7. 행과 열의 합
아래 배열의 각 행의 합과 각 열의 합을 구하세요.

```python
arr = np.array([[1, 2, 3],  # 넘파이 배열을 만듭니다.
                [4, 5, 6],
                [7, 8, 9]])
```

<details><summary>정답</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

print(np.sum(arr, axis=1))  # [ 6 15 24]
print(np.sum(arr, axis=0))  # [12 15 18]

```
</details>

In [ ]:
### 여기에 작성하세요
arr = np.array([[1, 2, 3],  # 넘파이 배열을 만듭니다.
                [4, 5, 6],
                [7, 8, 9]])

### 문제 8. 최댓값과 최솟값
아래 배열에서 최댓값과 최솟값, 그리고 각각의 위치(인덱스)를 구하세요.

```python
arr = np.array([10, 50, 30, 70, 20])  # 넘파이 배열을 만듭니다.
```

<details><summary>정답</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

print(np.max(arr))        # 70
print(np.min(arr))        # 10
print(np.argmax(arr))     # 3
print(np.argmin(arr))     # 0

```
</details>

In [ ]:
### 여기에 작성하세요
arr = np.array([10, 50, 30, 70, 20])  # 넘파이 배열을 만듭니다.

### 문제 9. 전치
아래 배열을 전치(transpose)하세요.

```python
arr = np.array([[1, 2],  # 넘파이 배열을 만듭니다.
                [3, 4],
                [5, 6]])
```

<details><summary>정답</summary>

```python
# 풀이 흐름: 실습에 사용할 Numpy 배열을 준비합니다.
# 배열 연산으로 원하는 결과를 계산합니다.

print(arr.T)  # 결과를 화면에 출력합니다.
# [[1 3 5]
#  [2 4 6]]

```
</details>

In [ ]:
### 여기에 작성하세요

### 문제 10. 조건에 맞는 값 바꾸기
아래 배열에서 5보다 큰 값만 0으로 바꾸세요.

```python
arr = np.array([1, 6, 3, 8, 5, 10])  # 넘파이 배열을 만듭니다.
```

<details><summary>정답</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

arr[arr > 5] = 0  # 새 파생 변수를 만들어 저장합니다.
print(arr)  # 결과를 화면에 출력합니다.
# [1 0 3 0 5 0]

```
</details>

In [ ]:
### 여기에 작성하세요
arr = np.array([1, 6, 3, 8, 5, 10])  # 넘파이 배열을 만듭니다.

### 문제 11. 행렬 곱셈
아래 배열을 이용하여 행렬 곱셈을 수행하세요.

```python
a = np.array([[1, 2],  # 넘파이 배열을 만듭니다.
              [3, 4]])
b = np.array([[5, 6],  # 넘파이 배열을 만듭니다.
              [7, 8]])
```

<details><summary>정답</summary>

```python
# 풀이 흐름: 실습에 사용할 Numpy 배열을 준비합니다.
# 배열 연산으로 원하는 결과를 계산합니다.

print(np.matmul(a, b))  # 결과를 화면에 출력합니다.
# [[19 22]
#  [43 50]]

```
</details>

In [ ]:
### 여기에 작성하세요
a = np.array([[1, 2],  # 넘파이 배열을 만듭니다.
              [3, 4]])
b = np.array([[5, 6],  # 넘파이 배열을 만듭니다.
              [7, 8]])

### 문제 12. 표준화
아래 배열을 정규화(평균=0, 표준편차=1)하세요.

```python
arr = np.array([1, 2, 3, 4, 5])  # 넘파이 배열을 만듭니다.
```
정규화 공식 (x - mean(x)) / std(x)
<details><summary>정답</summary>

```python
# 풀이 흐름: 실습에 사용할 Numpy 배열을 준비합니다.
# 배열 연산으로 원하는 결과를 계산합니다.

normalized = (arr - np.mean(arr)) / np.std(arr)  # 평균을 계산합니다.
print(normalized)  # 결과를 화면에 출력합니다.
# [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

```
</details>

In [ ]:
### 여기에 작성하세요
arr = np.array([1, 2, 3, 4, 5])  # 넘파이 배열을 만듭니다.


### 문제 13. FizzBuzz 배열
아래 배열에서 3의 배수는 `"Fizz"`, 5의 배수는 `"Buzz"`, 15의 배수는 `"FizzBuzz"`로 바꾸고 출력하세요.  

```python
arr = np.arange(1, 21)  # 범위 기반 숫자 배열을 만듭니다.
```

<details><summary>정답</summary>

```python
# 풀이 흐름: 실습에 사용할 Numpy 배열을 준비합니다.
# 배열 연산으로 원하는 결과를 계산합니다.

arr_str = arr.astype("object")  # 자료형을 변환합니다.

arr_str[arr % 15 == 0] = "FizzBuzz"
arr_str[(arr % 3 == 0) & (arr % 15 != 0)] = "Fizz"
arr_str[(arr % 5 == 0) & (arr % 15 != 0)] = "Buzz"

print(arr_str)  # 결과를 화면에 출력합니다.
# [1 2 'Fizz' 4 'Buzz' 'Fizz' 7 8 'Fizz' 'Buzz' 11 'Fizz' 13 14 'FizzBuzz'
#  16 17 'Fizz' 19 'Buzz']

```
</details>


In [ ]:
arr = np.arange(1, 21)  # 범위 기반 숫자 배열을 만듭니다.

### 문제 14. 리스트와 Numpy 속도 비교
1부터 1,000,000까지의 숫자를 제곱한 결과를 각각 파이썬 리스트와 넘파이 배열을 이용해 계산하고,
두 방법의 실행 시간을 각각 출력하여 비교하세요.

<details><summary>정답</summary>

```python
# 풀이 흐름: 실습에 사용할 Numpy 배열을 준비합니다.
# 배열 연산으로 원하는 결과를 계산합니다.

import time  # 실행 시간을 측정하기 위한 모듈입니다.
import numpy as np  # 배열 계산을 위한 Numpy입니다.

# 리스트 연산
start = time.time()  # 현재 시간을 초 단위로 기록합니다.
list_result = [x**2 for x in range(1, 1_000_001)]  # 리스트 방식으로 제곱 결과를 만듭니다.
end = time.time()  # 현재 시간을 초 단위로 기록합니다.
print("리스트 연산 시간:", end - start)  # 결과를 화면에 출력합니다.

# 넘파이 연산
arr = np.arange(1, 1_000_001)  # 실습에 사용할 배열을 만듭니다.
start = time.time()  # 현재 시간을 초 단위로 기록합니다.
np_result = arr ** 2  # 넘파이 벡터 연산으로 제곱합니다.
end = time.time()  # 현재 시간을 초 단위로 기록합니다.
print("넘파이 연산 시간:", end - start)  # 결과를 화면에 출력합니다.

```
</details>


In [ ]:
### 여기에 작성하세요


### 체크포인트
- 배열의 축(axis)을 기준으로 행·열 계산을 구분할 수 있다.
- 불린 마스킹으로 조건에 맞는 값만 고르거나 바꿀 수 있다.
- `reshape`, `stack`, `concatenate`, 행렬곱을 필요한 상황에 맞게 사용할 수 있다.


# 1. 들어가기

데이터 분석은 크게 **세 단계**로 진행됩니다.

1. **데이터 탐색**  
   데이터를 불러오고, 구조와 크기를 확인합니다.  

2. **기초 통계로 요약**  
   평균, 중앙값, 최댓값, 최솟값 같은 수치로 데이터를 간단히 요약합니다.  

3. **시각화**  
   히스토그램, 박스플롯 같은 그래프를 통해 데이터를 직관적으로 이해합니다.  

이러한 과정 전체를 **EDA(Exploratory Data Analysis, 탐색적 데이터 분석)** 라고 합니다.  
EDA는 데이터를 처음 접했을 때 숨겨진 패턴을 찾고, 이상치를 확인하며, 가설을 세우는 데 중요한 단계입니다.

`Pandas`로 데이터를 다루고, `Matplotlib`와 `Seaborn`으로 시각화하는 흐름을 익힙니다.


# 2. 데이터 준비 & Pandas 기초

## 2.1 Pandas란?
- 파이썬에서 데이터를 표(table) 형태로 다루는 라이브러리
- **엑셀과 비슷한 DataFrame**을 제공
- 데이터 탐색, 전처리, 분석의 표준 도구

```python
import pandas as pd  # 표 형태 데이터를 다루는 라이브러리입니다.
```


## 2.2 데이터 불러오기

### `pd.read_csv("파일경로")`
- CSV 파일(콤마로 구분된 텍스트 파일)을 불러와서 **DataFrame**으로 변환  
- **DataFrame**: 행(row)과 열(column)로 이루어진 2차원 데이터 구조


In [ ]:
import pandas as pd  # 표 형태 데이터를 다루는 라이브러리입니다.

# Titanic 데이터 불러오기 (예시)
titanic = pd.read_csv("titanic/train.csv")  # CSV 파일을 데이터프레임으로 읽습니다.

# Bike Sharing 데이터 불러오기 (예시)
bike = pd.read_csv("자전거수요예측/train.csv")  # CSV 파일을 데이터프레임으로 읽습니다.

## 2.3 데이터 구조 확인

### `df.shape`
- DataFrame의 (행 개수, 열 개수)를 튜플 형태로 반환

### `df.columns`
- DataFrame의 열 이름 확인


In [ ]:
print(titanic.shape)     # (891, 12) → 891명, 12개 속성
print(titanic.columns)   # 컬럼명 리스트

## 2.4 데이터 미리보기

### `df.head()`
- DataFrame의 앞부분 5행을 보여줌  
- 데이터가 어떻게 생겼는지 빠르게 확인할 때 사용

### `df.tail()`
- DataFrame의 뒷부분 5행을 보여줌  


In [ ]:
titanic.head()

In [ ]:
titanic.tail()

## 2.5 데이터 요약 정보

### `df.info()`
- 각 열의 자료형과 결측치(null) 여부를 보여줌

### `df.describe()`
- 기본적인 통계값(평균, 표준편차, 최소/최대, 사분위수)을 수치형 데이터에 대해 요약


In [ ]:
titanic.info()

In [ ]:
titanic.describe()  # 기초 통계량을 확인합니다.

## 2.6 데이터 정렬

### `df.sort_values("컬럼명")`
- 특정 열 기준으로 정렬  
- 오름차순 / 내림차순 지정 가능 (`ascending=True/False`)


In [ ]:
# 나이를 기준으로 오름차순 정렬
titanic.sort_values("Age").head()  # 값 기준으로 정렬합니다.

In [ ]:
# 요금을 기준으로 내림차순 정렬
titanic.sort_values("Fare", ascending=False).head()  # 값 기준으로 정렬합니다.

## 2.7 인덱싱 & 선택

- `loc[]`: 행/열 이름(label) 기반 접근  
- `iloc[]`: 행/열 번호(index) 기반 접근


In [ ]:
# 특정 행 선택
titanic.loc[titanic['PassengerId']==1]# 첫 번째 승객 정보 (이름 기반)

In [ ]:
# 특정 행 선택
titanic.loc[titanic['Age']==22, 'Age'] # 나이가 22인 사람의 Age 컬럼만 보기

In [ ]:
titanic.iloc[0] # 첫 번째 승객 정보 (숫자 기반)

In [ ]:
# 특정 열 선택
print(titanic["Age"].head())   # 나이 컬럼만

## 2.8 데이터 수정/추가

- 새로운 열을 추가하거나 값 수정 가능


In [ ]:
# 나이를 10살 단위 구간으로 나누는 새로운 열 추가
titanic["AgeGroup"] = (titanic["Age"] // 10) * 10
titanic[["Age", "AgeGroup"]].head()

### ✅ 체크포인트
- `pd.read_csv()` 로 CSV 파일을 불러와 DataFrame을 만든다.  
- `shape`, `columns`, `head()`, `tail()` 로 데이터 구조를 빠르게 파악한다.  
- `info()`, `describe()` 로 데이터 타입과 통계 요약을 확인할 수 있다.  
- `sort_values()` 로 정렬, `loc[]`와 `iloc[]`로 인덱싱한다.  
- 새로운 열을 추가하거나 값 수정이 가능하다.


# 3. 기술 통계 기초

## 3.1 데이터의 종류
- **수치형 데이터 (Numerical)**  
  → 숫자로 된 데이터 (예: 나이, 요금, 대여량)  

- **범주형 데이터 (Categorical)**  
  → 그룹/범주를 나타내는 데이터 (예: 성별, 클래스, 요일)


## 3.2 대표값 (중심 경향)
데이터를 대표하는 값들

- **평균 (mean)**: 모든 값을 더한 뒤 개수로 나눔  
- **중앙값 (median)**: 데이터를 크기순으로 정렬했을 때 한가운데 값  
- **최빈값 (mode)**: 가장 많이 등장하는 값


In [ ]:
print(titanic["Age"].median())    # 중앙값 나이
print(titanic["Age"].mean())      # 평균 나이
print(titanic["Age"].mode())      # 최빈값 나이

# 👉 승객 나이(`Age`) 평균과 중앙값은 다를 수 있다.

## 3.3 범위와 분포
데이터의 퍼짐 정도를 나타내는 값들

- **최소값 (min)**, **최대값 (max)**  
- **사분위수 (quantile)**  
  - 데이터를 4등분한 구간의 경계  
  - 25%, 50%(=중앙값), 75% 지점  
- **분산 (variance)**: 데이터가 평균에서 얼마나 떨어져 있는지  
- **표준편차 (std)**: 분산의 제곱근 → 데이터의 흩어진 정도  


In [ ]:
print(titanic["Age"].min())      # 최소 나이
print(titanic["Age"].max())      # 최대 나이
print(titanic["Age"].quantile([0.25, 0.5, 0.75]))  # 사분위수
print(titanic["Age"].std())      # 표준편차

## 3.4 Pandas describe()
- `df.describe()` 로 한 번에 기초 통계 요약 제공
- 기본적으로 수치형 데이터만 보여줌
- 옵션 `include="all"` → 범주형 데이터까지 요약  


In [ ]:
titanic.describe()  # 기초 통계량을 확인합니다.

### ✅ 체크포인트
- **평균, 중앙값, 최빈값**은 데이터의 중심을 요약하는 대표값이다.  
- **최솟값, 최댓값, 사분위수, 표준편차**는 데이터의 퍼짐 정도를 설명한다.  
- Pandas의 `describe()`는 여러 통계값을 한 번에 확인할 수 있다.  


# 4. 데이터 시각화 기본 (Matplotlib & Seaborn)



## 4.1 Matplotlib & Seaborn 소개
- **Matplotlib**: 파이썬의 가장 기본적인 시각화 라이브러리  
- **Seaborn**: Matplotlib 기반으로, 통계 시각화에 특화된 라이브러리


In [ ]:
import matplotlib.pyplot as plt  # 그래프를 그리는 시각화 도구입니다.
import seaborn as sns  # 통계 그래프 시각화 도구입니다.

## 4.2 히스토그램 (Histogram)
- 데이터를 구간(bin)으로 나누어, 각 구간에 속한 데이터 개수를 세어 표시  
- 데이터의 분포 모양을 직관적으로 확인 가능


In [ ]:
# Titanic 예시: 승객들의 나이 분포 확인 
sns.histplot(titanic["Age"].dropna(), bins=20, kde=False)  # 결측치가 있는 행/열을 제거합니다.
plt.show()  # 그래프를 화면에 출력합니다.

## 4.3 박스플롯 (Boxplot)
- 데이터의 **사분위수(25%, 50%, 75%)** 와 **이상치(outlier)** 를 한눈에 보여줌  
- 중앙값과 데이터 퍼짐 정도를 시각적으로 확인 가능  


In [ ]:
# Titanic 예시: 남성과 여성의 나이 분포 비교  
sns.boxplot(x="Sex", y="Age", data=titanic)  # 시본 그래프를 그립니다.
plt.show()  # 그래프를 화면에 출력합니다.



## 4.4 KDE Plot (확률 밀도 함수)
- 히스토그램을 부드럽게 표현한 곡선 그래프  
- 데이터가 어느 구간에 몰려 있는지 직관적으로 파악 가능  


In [ ]:
# Titanic 예시: 승객 나이의 전체 분포 곡선  
sns.kdeplot(titanic["Age"].dropna(), shade=True)  # 결측치가 있는 행/열을 제거합니다.
plt.show()  # 그래프를 화면에 출력합니다.



## 4.5 여러 분포 비교
- 그룹별로 색을 다르게 해서 히스토그램이나 KDE plot 그리기  


In [ ]:
# Titanic 예시: 성별에 따른 나이 분포 비교  
sns.histplot(data=titanic, x="Age", hue="Sex", bins=20, kde=True)  # 시본 그래프를 그립니다.
plt.show()  # 그래프를 화면에 출력합니다.

### ✅ 체크포인트
- **히스토그램**: 데이터의 빈도 분포 확인  
- **박스플롯**: 사분위수와 이상치 확인  
- **KDE plot**: 데이터 분포를 곡선으로 표현  
- 그룹별 분포 비교 가능 (예: 성별, 등급, 계절 등)  


# 5. 다양한 데이터 분포 살펴보기

## 5.1 정규분포 (Normal Distribution)
- 데이터가 **종 모양(bell curve)** 으로 퍼져 있는 분포  
- 평균을 중심으로 대칭  
- 많은 자연현상과 사회현상에서 나타나는 가장 중요한 분포  

예: 사람의 키, 시험 점수


In [ ]:
# Titanic 예시: 승객 나이는 대체로 정규분포에 가까운 모양을 보임  
sns.histplot(titanic["Age"].dropna(), kde=True)  # 결측치가 있는 행/열을 제거합니다.
plt.show()  # 그래프를 화면에 출력합니다.

## 5.2 비대칭 분포 (Skewness)
- 분포가 한쪽으로 치우쳐 있는 경우  
- **왼쪽 꼬리(음의 왜도)**: 평균 < 중앙값  
- **오른쪽 꼬리(양의 왜도)**: 평균 > 중앙값  

예: 소득 분포 (고소득자가 소수 존재 → 오른쪽 꼬리)


In [ ]:
# Bike Sharing 예시: 특정 날씨나 계절 때문에 수요가 치우칠 수 있음  
sns.histplot(bike["count"], kde=True)  # 시본 그래프를 그립니다.
plt.show()  # 그래프를 화면에 출력합니다.

### ✅ 체크포인트
- **정규분포**: 평균 중심, 대칭적인 종 모양 분포  
- **왜도(Skewness)**: 분포가 한쪽으로 치우쳐 있는 정도

# 6. Pandas와 시각화 연계

## 6.1 DataFrame 자체로 그래프 그리기
- Pandas는 Matplotlib을 기반으로 간단한 시각화를 지원
- `df.plot()` 메서드 사용


In [ ]:
# Bike Sharing 데이터의 월별 평균 대여량
bike['month'] = pd.to_datetime(bike['datetime']).dt.month  # 문자열 날짜를 datetime으로 바꿉니다.
bike.groupby("month")["count"].mean().plot(kind="bar")  # 그룹별로 데이터를 묶습니다.
plt.show()  # 그래프를 화면에 출력합니다.

## 6.2 시리즈(Series) 그래프
- 특정 열(Series)에 대해서 바로 시각화 가능


In [ ]:
titanic["Age"].plot(kind="hist", bins=20, title="Age Distribution")
plt.show()  # 그래프를 화면에 출력합니다.

## 6.3 그룹별 집계와 시각화
- `groupby()`로 데이터를 그룹화하고 요약 통계 계산
- 그 결과를 시각화와 연결


In [ ]:
# 성별에 따른 평균 생존율
survival_rate = titanic.groupby("Sex")["Survived"].mean()  # 그룹별로 데이터를 묶습니다.
survival_rate.plot(kind="bar", title="Survival Rate by Sex")
plt.show() # titanic 예시: 여성의 생존율이 남성보다 훨씬 높음 

## 6.4 Seaborn과 함께 사용하기
- Pandas DataFrame은 Seaborn의 입력 데이터로 바로 활용 가능
- Seaborn은 더 세련되고 다양한 시각화 제공


In [ ]:
# 클래스별 요금 분포
sns.boxplot(x="Pclass", y="Fare", data=titanic)  # 시본 그래프를 그립니다.
plt.show()  # 그래프를 화면에 출력합니다.

### ✅ 체크포인트
- Pandas의 `plot()`으로 DataFrame과 Series를 빠르게 시각화할 수 있다.  
- `groupby()`를 활용하면 그룹별 통계를 계산하고 바로 그래프와 연결할 수 있다.  
- Seaborn은 Pandas DataFrame을 직접 받아 고급 시각화를 지원한다.  


## 통계와 시각화 추가 연습

기술 통계와 그래프를 함께 사용해 데이터의 분포와 그룹별 차이를 확인합니다.


### 문제 1. 성별별 나이 분포
Titanic 데이터에서 **성별별 나이 분포**를 박스플롯으로 그려보세요.
- `sns.boxplot()`을 사용합니다.
- 남성과 여성의 나이 분포 차이를 관찰합니다.

<details>
<summary>정답 보기</summary>

```python
# 풀이 흐름: 그래프로 확인할 값을 먼저 계산합니다.
# 마지막에 그래프나 표로 결과를 확인합니다.

sns.boxplot(x="Sex", y="Age", data=titanic.dropna(subset=["Age"]))  # Seaborn으로 그래프를 그립니다.
plt.title("Age Distribution by Sex")  # 그래프 제목을 설정합니다.
plt.xlabel("Sex")  # x축 이름을 설정합니다.
plt.ylabel("Age")  # y축 이름을 설정합니다.
plt.show()  # 그래프를 화면에 표시합니다.

```
</details>


In [ ]:
# 여기에 작성하세요


### 문제 2. 월별 평균 대여량 시각화
Bike Sharing 데이터에서 **월별 평균 대여량**을 막대그래프로 시각화하세요.  
- `groupby("month")["count"].mean()` 활용  
- 계절에 따른 수요 차이를 설명해보세요.


<details>
<summary>정답</summary>

```python
# 풀이 흐름: 그래프로 확인할 값을 먼저 계산합니다.
# 마지막에 그래프나 표로 결과를 확인합니다.

import pandas as pd  # 표 데이터를 다루기 위한 Pandas입니다.
import matplotlib.pyplot as plt  # 그래프를 그리기 위한 Matplotlib입니다.

# month 컬럼이 없을 수 있으므로 보강
if "month" not in bike.columns:  # 조건을 확인합니다.
    # datetime에서 월 추출
    bike["month"] = pd.to_datetime(bike["datetime"]).dt.month  # 문자열 날짜를 datetime으로 바꿉니다.

monthly_mean = bike.groupby("month")["count"].mean()  # 그룹별로 데이터를 묶습니다.

monthly_mean.plot(kind="bar")  # 계산 결과를 그래프로 그립니다.
plt.title("Average Bike Demand by Month")  # 그래프 제목을 설정합니다.
plt.xlabel("Month")  # x축 이름을 설정합니다.
plt.ylabel("Average Count")  # y축 이름을 설정합니다.
plt.show()  # 그래프를 화면에 표시합니다.

```
</details>


In [ ]:
# 여기에 작성하세요
import matplotlib.pyplot as plt  # 그래프를 그리는 시각화 도구입니다.
import seaborn as sns  # 통계 그래프 시각화 도구입니다.

### 문제 3. 평균, 중앙값, 최빈값 비교
Titanic 데이터의 `Age` 컬럼에 대해 **평균, 중앙값, 최빈값**을 구하고 비교하세요.  
- `mean()`, `median()`, `mode()` 활용  
- 왜 이 값들이 서로 다른지 설명해보세요. (이상치나 분포의 왜도 때문일 수 있음)

<details>
<summary>정답</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

import numpy as np  # 배열 계산을 위한 Numpy입니다.

age = titanic["Age"].dropna()  # 결측치가 있는 행/열을 제거합니다.

mean_age = age.mean()  # 나이 평균값을 계산합니다.
median_age = age.median()  # 나이 중앙값을 계산합니다.
mode_age = age.mode()  # Series 반환(복수 최빈값 가능)

print("평균:", mean_age)  # 결과를 화면에 출력합니다.
print("중앙값:", median_age)  # 결과를 화면에 출력합니다.
print("최빈값:", list(mode_age.values))  # 결과를 화면에 출력합니다.

# 해석 포인트(예시)
# - 평균과 중앙값 차이가 크면 분포가 치우쳤거나(outlier 영향) 결측치 처리 이슈가 있을 수 있음

```
</details>


In [ ]:
# 여기에 작성하세요
import matplotlib.pyplot as plt  # 그래프를 그리는 시각화 도구입니다.
import seaborn as sns  # 통계 그래프 시각화 도구입니다.

### 문제 4. 히스토그램과 KDE 비교
Bike Sharing 데이터에서 `count` 분포를 히스토그램과 KDE plot으로 시각화하세요.  
- 두 그래프를 비교해보고, KDE가 어떤 장점을 가지는지 설명해보세요.

<details>
<summary>정답</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

import matplotlib.pyplot as plt  # 그래프를 그리기 위한 Matplotlib입니다.

# 히스토그램
sns.histplot(bike["count"], bins=30, kde=False)  # Seaborn으로 그래프를 그립니다.
plt.title("Histogram of Bike Demand (count)")  # 그래프 제목을 설정합니다.
plt.xlabel("count")  # x축 이름을 설정합니다.
plt.ylabel("frequency")  # y축 이름을 설정합니다.
plt.show()  # 그래프를 화면에 표시합니다.

# KDE plot
sns.kdeplot(bike["count"], fill=True)  # Seaborn으로 그래프를 그립니다.
plt.title("KDE of Bike Demand (count)")  # 그래프 제목을 설정합니다.
plt.xlabel("count")  # x축 이름을 설정합니다.
plt.ylabel("density")  # y축 이름을 설정합니다.
plt.show()  # 그래프를 화면에 표시합니다.

# 비교 포인트(예시)
# - 히스토그램: 구간별 빈도 확인에 유리 (bin 크기에 따라 모양 영향)
# - KDE: 분포의 전반적 형태를 부드럽게 파악 (피크/꼬리 관찰에 유리)

```
</details>


In [ ]:
# 여기에 작성하세요
import matplotlib.pyplot as plt  # 그래프를 그리는 시각화 도구입니다.
import seaborn as sns  # 통계 그래프 시각화 도구입니다.

### 문제 5. 객실 등급별 생존율
Titanic 데이터에서 **Pclass(객실 등급)** 에 따른 **생존율**을 계산하고, 막대그래프로 표현하세요.  
- `groupby("Pclass")["Survived"].mean()` 활용  
- 어떤 등급일수록 생존율이 높았는지 해석해보세요.

<details>
<summary>정답</summary>

```python
# 풀이 흐름: 그래프로 확인할 값을 먼저 계산합니다.
# 마지막에 그래프나 표로 결과를 확인합니다.

import matplotlib.pyplot as plt  # 그래프를 그리기 위한 Matplotlib입니다.

survival_by_pclass = titanic.groupby("Pclass")["Survived"].mean()  # 그룹별로 데이터를 묶습니다.

survival_by_pclass.plot(kind="bar")  # 계산 결과를 그래프로 그립니다.
plt.title("Survival Rate by Passenger Class (Titanic)")  # 그래프 제목을 설정합니다.
plt.xlabel("Pclass")  # x축 이름을 설정합니다.
plt.ylabel("Survival Rate")  # y축 이름을 설정합니다.
plt.ylim(0, 1)
plt.show()  # 그래프를 화면에 표시합니다.

# 해석 포인트(예시)
# - 일반적으로 1등석의 생존율이 높게 나타나는 경향
# - 계층/구역/구조적 요인이 결과에 반영될 수 있음

```
</details>


In [ ]:
# 여기에 작성하세요
import matplotlib.pyplot as plt  # 그래프를 그리는 시각화 도구입니다.

### 체크포인트
- 평균·중앙값·최빈값을 비교하면 분포의 치우침을 짐작할 수 있다.
- 히스토그램, KDE, 박스플롯은 같은 데이터를 서로 다른 관점에서 보여준다.
- `groupby()` 결과를 그래프로 연결하면 그룹별 차이가 더 잘 보인다.


# 7. 데이터 다듬기

데이터는 항상 깨끗하지 않습니다.  
- **결측값 (missing values)**: 데이터가 비어 있는 값  
- **중복값 (duplicates)**: 동일한 데이터가 여러 번 등장  
- **이상점 (outliers)**: 다른 값들과 동떨어진 극단적인 값  

이러한 문제를 처리해야 **신뢰할 수 있는 분석**을 할 수 있습니다.  



## 7.1 결측값 처리

### 결측값 확인
- `isna()`: 값이 NaN인지 True/False 반환  
- `sum()`: 결측치 개수 세기


In [ ]:
# Titanic 데이터 예시
print(titanic.isna().sum())  # 문자열을 정수로 바꿉니다.

### 결측값 제거
- `dropna()`: 결측치가 있는 행/열 삭제  

In [ ]:
titanic_drop = titanic.dropna(subset=["Age"])  # Age가 NaN인 행 제거
print(titanic_drop.shape)  # 문자열을 정수로 바꿉니다.

### 결측값 대체
- `fillna(값)`: 결측치를 특정 값으로 채우기

In [ ]:
# Bike Sharing 예시: 기온/습도 결측치를 평균값이나 중간값으로 채울 수 있음  
# 평균 나이로 채우기
mean_age = titanic["Age"].mean()
titanic["Age_filled"] = titanic["Age"].fillna(mean_age)  # 결측치를 지정한 값으로 채웁니다.

## 7.2 중복값 처리

### 중복 확인
- `duplicated()`: 각 행이 중복인지 True/False 반환  
- `sum()`: 중복 개수 세기


In [ ]:
print(titanic.duplicated().sum())  # 문자열을 정수로 바꿉니다.

### 중복 제거
- `drop_duplicates()`: 중복 행 제거  


In [ ]:
titanic_unique = titanic.drop_duplicates()
print(titanic_unique.shape)  # 문자열을 정수로 바꿉니다.

## 7.3 이상점 처리

### 이상점이란?
- 데이터 분포에서 일반적인 범위에서 크게 벗어난 값  
- 분석 결과를 왜곡할 수 있으므로 확인이 필요  

### 박스플롯으로 이상점 시각화
- 박스플롯은 사분위수를 기반으로 이상치를 확인  


In [ ]:
import seaborn as sns  # 통계 그래프 시각화 도구입니다.
import matplotlib.pyplot as plt  # 그래프를 그리는 시각화 도구입니다.

sns.boxplot(x=titanic["Age"])  # 시본 그래프를 그립니다.
plt.show()  # 그래프를 화면에 출력합니다.






### IQR(사분위 범위) 방식으로 이상점 탐지
- IQR = Q3 - Q1  
- 하한 = Q1 - 1.5 × IQR  
- 상한 = Q3 + 1.5 × IQR  
- 범위를 벗어난 값 = 이상점  



In [ ]:
# Bike Sharing 예시: 대여량(`count`)이 너무 비정상적으로 큰 날을 탐지할 수 있음  

Q1 = titanic["Age"].quantile(0.25)
Q3 = titanic["Age"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = titanic[(titanic["Age"] < lower_bound) | (titanic["Age"] > upper_bound)]
print(outliers[["Age"]])  # 문자열을 정수로 바꿉니다.

### ✅ 체크포인트
- **결측값**: `isna()`, `dropna()`, `fillna()`로 확인·삭제·대체할 수 있다.  
- **중복값**: `duplicated()`, `drop_duplicates()`로 처리할 수 있다.  
- **이상점**: 박스플롯과 IQR 방식을 활용해 탐지할 수 있다.  


# 8. 문자 데이터 가공

데이터 분석에서는 **문자열 처리**가 매우 자주 필요합니다.  
예를 들어, 승객 이름에서 호칭(Mr, Mrs 등)을 추출하거나, 텍스트 데이터를 정리할 때 사용됩니다.  

## 8.1 대소문자 처리
- `str.lower()` : 모두 소문자로 변환  
- `str.upper()` : 모두 대문자로 변환  
- `str.title()` : 단어의 첫 글자만 대문자로 변환  


In [ ]:
names = pd.Series([" Alice ", "BOB", "cHaRlIe "])  # 인덱스가 있는 1차원 데이터를 만듭니다.

print(names.str.lower())   # 소문자 변환
print(names.str.upper())   # 대문자 변환
print(names.str.title())   # 첫 글자만 대문자

## 8.2 문자열 공백 제거
- `str.strip()` : 앞뒤 공백 제거  
- `str.lstrip()` : 왼쪽 공백 제거  
- `str.rstrip()` : 오른쪽 공백 제거  


In [ ]:
print(names.str.strip())  # 양쪽 공백을 제거합니다.

## 8.3 문자열 분리
- `str.split("구분자")` : 구분자를 기준으로 분리 → 리스트 반환  
- `str.get(인덱스)` 또는 `.str[인덱스]`로 특정 위치 추출  


In [ ]:
# Titanic 예시: 승객 이름에서 호칭(Mr, Mrs, Miss 등)을 추출  
titanic["Title"] = titanic["Name"].str.split(",").str[1].str.split(".").str[0].str.strip()  # 문자열을 기준에 따라 나눕니다.
print(titanic[["Name", "Title"]].head())  # 문자열을 정수로 바꿉니다.


## 8.4 문자열 대체
- `str.replace("찾을문자", "바꿀문자")`  


In [ ]:
city = pd.Series(["New York", "Los Angeles", "new york"])  # 인덱스가 있는 1차원 데이터를 만듭니다.

print(city.str.replace("New York", "NYC", case=False))  # 문자열 일부를 바꿉니다.

## 8.5 조건 필터링 (문자열 포함 여부)
- `str.contains("문자열")`: 특정 문자가 포함된 행만 True  


In [ ]:
mask = titanic["Name"].str.contains("Smith")
print(titanic[mask][["Name", "Age"]])  # 문자열을 정수로 바꿉니다.

### ✅ 체크포인트
- 문자열을 소문자/대문자/타이틀 케이스로 변환할 수 있다.  
- 공백 제거, 문자열 분리(split), 대체(replace) 등의 전처리 작업이 가능하다.  
- `.str.contains()`로 특정 문자를 포함한 행을 쉽게 찾을 수 있다.  
- Titanic 데이터에서는 이름(`Name`)에서 호칭 추출, 특정 성씨 검색 등에 활용할 수 있다.  


## DataFrame 추가 연습

결측값, 이상점, 문자열, 날짜, 조인, 그룹화를 이어서 연습합니다. 앞에서 만든 `titanic`, `bike` DataFrame을 사용합니다.


In [ ]:
# 앞쪽 데이터 불러오기 셀을 실행하지 않았다면 이 셀을 먼저 실행합니다.
import pandas as pd  # 표 형태 데이터를 다루는 라이브러리입니다.

titanic = pd.read_csv("titanic/train.csv")  # CSV 파일을 데이터프레임으로 읽습니다.
bike = pd.read_csv("자전거수요예측/train.csv")  # CSV 파일을 데이터프레임으로 읽습니다.

### 문제 1. 결측값 처리
Titanic 데이터의 `Age` 컬럼에서 결측치 개수를 확인하고, 평균값으로 채우세요.  

<details>
<summary>정답 보기</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

# 결측치 개수 확인
print(titanic["Age"].isna().sum())  # 결과를 화면에 출력합니다.

# 평균값으로 채우기
mean_age = titanic["Age"].mean()  # 나이 평균값을 계산합니다.
titanic["Age_filled"] = titanic["Age"].fillna(mean_age)  # 결측치를 지정한 값으로 채웁니다.

```
</details>

In [ ]:
# 여기에 작성하세요

### 문제 2. 이상점 탐지
Titanic 데이터에서 `Fare` 컬럼의 이상점을 IQR 방식을 사용해 탐지하세요.  

<details>
<summary>정답 보기</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

Q1 = titanic["Fare"].quantile(0.25) # 하위 25%
Q3 = titanic["Fare"].quantile(0.75) # 상위 25%
IQR = Q3 - Q1  # 중간 50% 범위인 사분위 범위입니다.

lower_bound = Q1 - 1.5 * IQR  # 이상치 판단에 사용할 하한값입니다.
upper_bound = Q3 + 1.5 * IQR  # 이상치 판단에 사용할 상한값입니다.

outliers = titanic[(titanic["Fare"] < lower_bound) | (titanic["Fare"] > upper_bound)]  # 이상치로 판단된 행만 모읍니다.
print(outliers[["Fare"]].head())  # 결과를 화면에 출력합니다.

```
</details>

In [ ]:
# 여기에 작성하세요

### 문제 3. 문자열 가공
Titanic 데이터의 `Name` 컬럼에서 승객 호칭(예: Mr, Mrs, Miss)을 추출하여 새로운 컬럼 `Title`을 만드세요.  

<details>
<summary>정답 보기</summary>

```python
# 풀이 흐름: 문자열을 다루기 쉬운 형태로 정리합니다.
# 필요한 값만 추출하거나 비교합니다.

titanic["Title"] = titanic["Name"].str.split(",").str[1].str.split(".").str[0].str.strip()  # 문자열을 기준에 따라 나눕니다.
print(titanic[["Name", "Title"]].head())  # 결과를 화면에 출력합니다.

```
</details>



In [ ]:
# 여기에 작성하세요


### 문제 4. 구간화
Titanic 데이터의 `Age` 컬럼을 기준으로 나이를 `Child(0-12), Teen(13-19), Adult(20-64), Senior(65+)` 구간으로 나누어 새로운 컬럼을 추가하세요.  

<details>
<summary>정답 보기</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

bins = [0, 12, 19, 64, 100]  # 나눌 구간의 경계값입니다.
labels = ["Child", "Teen", "Adult", "Senior"]  # 각 구간에 붙일 이름입니다.

titanic["AgeGroup"] = pd.cut(titanic["Age"], bins=bins, labels=labels)  # 연속값을 구간 범주로 나눕니다.
print(titanic[["Age", "AgeGroup"]].head())  # 결과를 화면에 출력합니다.

```
</details>

In [ ]:
# 여기에 작성하세요
bins = [0, 12, 19, 64, 100]
labels = ["Child", "Teen", "Adult", "Senior"]

### 문제 5. 날짜 처리
Bike Sharing 데이터에서 `datetime` 컬럼을 datetime 타입으로 변환하고, `year`, `month`, `weekday` 컬럼을 추출하세요.  

<details>
<summary>정답 보기</summary>

```python
# 풀이 흐름: 문자열 날짜를 datetime 타입으로 바꿉니다.
# 날짜에서 필요한 값을 뽑아 집계합니다.

bike["datetime"] = pd.to_datetime(bike["datetime"])  # 문자열 날짜를 datetime으로 바꿉니다.
bike["year"] = bike["datetime"].dt.year  # 새 파생 변수를 만들어 저장합니다.
bike["month"] = bike["datetime"].dt.month  # 새 파생 변수를 만들어 저장합니다.
bike["weekday"] = bike["datetime"].dt.weekday  # 새 파생 변수를 만들어 저장합니다.

print(bike[["datetime", "year", "month", "weekday"]].head())  # 결과를 화면에 출력합니다.

```
</details>

In [ ]:
# 여기에 작성하세요

### 문제 6. 데이터 합치기
아래 두 DataFrame을 `ID` 컬럼을 기준으로 merge하세요.  


df_left = pd.DataFrame({"ID": [1, 2, 3], "Age": [22, 35, 58]})
df_right = pd.DataFrame({"ID": [2, 3, 4], "City": ["Seoul", "Busan", "Incheon"]})


<details>
<summary>정답 보기</summary>

```python
# 풀이 흐름: 합칠 두 DataFrame을 준비합니다.
# 기준 컬럼을 정해 원하는 방식으로 합칩니다.

df_merge = pd.merge(df_left, df_right, on="ID", how="inner")  # 공통 키를 기준으로 데이터프레임을 합칩니다.
print(df_merge)  # 결과를 화면에 출력합니다.

```
</details>

In [ ]:
# 여기에 작성하세요

### 문제 7. 그룹화 & 피벗 테이블
Titanic 데이터에서 성별(`Sex`)과 객실 등급(`Pclass`)별 평균 생존율을 구하고, 피벗 테이블로 요약하세요.  

<details>
<summary>정답 보기</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

# groupby
print(titanic.groupby(["Sex", "Pclass"])["Survived"].mean())  # 그룹별로 데이터를 묶습니다.

# pivot_table
pivot = titanic.pivot_table(values="Survived", index="Sex", columns="Pclass", aggfunc="mean")  # 행과 열 기준으로 요약표를 만듭니다.
print(pivot)  # 결과를 화면에 출력합니다.

```
</details>

In [ ]:
# 여기에 작성하세요


### 문제 8. 다중 조건 불린 인덱싱
Titanic 데이터에서 Age >= 30 이고 Sex == "male" 인 행만 선택하여 Name, Age, Sex, Fare 컬럼만 보여주세요.

<details>
<summary>정답 보기</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

mask = (titanic["Age"] >= 30) & (titanic["Sex"] == "male")
print(titanic.loc[mask, ["Name", "Age", "Sex", "Fare"]].head())  # 결과를 화면에 출력합니다.

```
</details>

In [ ]:
# 여기에 작성하세요

### 문제 9. 사용자 정의 함수 적용
Age를 이용해 성인/미성년 여부를 표시하는 IsAdult 컬럼을 생성하세요. (나이 < 18 → 0, 그 외 → 1. 결측치는 -1)

<details>
<summary>정답 보기</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

def is_adult(age):  # 함수를 정의합니다.
    if pd.isna(age):  # 조건을 확인합니다.
        return -1  # 계산한 값을 함수 밖으로 돌려줍니다.
    return 1 if age >= 18 else 0  # 계산한 값을 함수 밖으로 돌려줍니다.

titanic["IsAdult"] = titanic["Age"].apply(is_adult)  # 함수를 각 값에 적용합니다.
print(titanic[["Age", "IsAdult"]].head())  # 결과를 화면에 출력합니다.

```
</details>

In [ ]:
# 여기에 작성하세요


### 문제 10. 분위수 기반 구간화(qcut)
Fare를 사분위수 기준 4개 구간으로 나누어 FareQuartile 컬럼을 생성하세요.

<details>
<summary>정답 보기</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

titanic["FareQuartile"] = pd.qcut(titanic["Fare"], q=4, labels=["Q1","Q2","Q3","Q4"])  # 분위수 기준으로 구간을 나눕니다.
print(titanic[["Fare", "FareQuartile"]].head())  # 결과를 화면에 출력합니다.

```
</details>

In [ ]:
# 여기에 작성하세요


### 문제 11. 시계열 리샘플링

Bike Sharing 데이터에서 datetime을 인덱스로 설정한 뒤, count의 월별 평균을 계산하세요.

<details>
<summary>정답 보기</summary>

```python
# 풀이 흐름: 문자열 날짜를 datetime 타입으로 바꿉니다.
# 날짜에서 필요한 값을 뽑아 집계합니다.

bike["datetime"] = pd.to_datetime(bike["datetime"])  # 문자열 날짜를 datetime으로 바꿉니다.
bike = bike.set_index("datetime")  # Bike Sharing 데이터를 DataFrame으로 불러옵니다.

monthly_mean = bike["count"].resample("M").mean()  # 월별 평균 대여량을 계산합니다.
print(monthly_mean.head())  # 결과를 화면에 출력합니다.

```
</details>

In [ ]:
# 여기에 작성하세요


### 문제 12. 다양한 조인 실습

아래 두 DataFrame으로 left join과 outer join 결과를 각각 만드세요.

```python
A = pd.DataFrame({"ID":[1,2,3], "City":["Seoul","Busan","Daegu"]})  # 데이터프레임을 직접 만듭니다.
B = pd.DataFrame({"ID":[2,3,4], "Income":[50,60,70]})  # 데이터프레임을 직접 만듭니다.
```

<details>
<summary>정답 보기</summary>

```python
# 풀이 흐름: 합칠 두 DataFrame을 준비합니다.
# 기준 컬럼을 정해 원하는 방식으로 합칩니다.

A = pd.DataFrame({"ID":[1,2,3], "City":["Seoul","Busan","Daegu"]})  # 데이터프레임을 직접 만듭니다.
B = pd.DataFrame({"ID":[2,3,4], "Income":[50,60,70]})  # 데이터프레임을 직접 만듭니다.

left_join = pd.merge(A, B, on="ID", how="left")  # 공통 키를 기준으로 데이터프레임을 합칩니다.
outer_join = pd.merge(A, B, on="ID", how="outer")  # 공통 키를 기준으로 데이터프레임을 합칩니다.

print(left_join)  # 결과를 화면에 출력합니다.
print(outer_join)  # 결과를 화면에 출력합니다.

```
</details>

In [ ]:
# 여기에 작성하세요
A = pd.DataFrame({"ID":[1,2,3], "City":["Seoul","Busan","Daegu"]})  # 데이터프레임을 직접 만듭니다.
B = pd.DataFrame({"ID":[2,3,4], "Income":[50,60,70]})  # 데이터프레임을 직접 만듭니다.

### 문제 13. 그룹 집계 다중 통계

Titanic 데이터에서 Sex별 Age의 평균·중앙값, Fare의 평균·최대값을 한 번에 구하세요.

<details>
<summary>정답 보기</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

agg_df = titanic.groupby("Sex").agg({  # 그룹별로 데이터를 묶습니다.
    "Age": ["mean", "median"],
    "Fare": ["mean", "max"]
})
print(agg_df)  # 결과를 화면에 출력합니다.

```
</details>

In [ ]:
# 여기에 작성하세요


### 문제 14. 피벗 테이블 + 전체 요약(margins)

Pclass(행) × Sex(열) 기준 Survived 평균을 피벗 테이블로 만들고, 행/열 합계를 포함하여 출력하세요.

<details>
<summary>정답 보기</summary>

```python
# 풀이 흐름: 필요한 값을 만들고 결과를 확인합니다.
# 문제에서 요구한 결과를 계산하고 확인합니다.

pivot = titanic.pivot_table(  # 행과 열 기준으로 요약표를 만듭니다.
    values="Survived",  # 집계할 생존 여부 값입니다.
    index="Pclass",  # 행 기준으로 사용할 객실 등급입니다.
    columns="Sex",  # 열 기준으로 사용할 성별입니다.
    aggfunc="mean",      # 각 그룹의 평균(생존율)
    margins=True,        # '전체 요약값' 행/열 추가 (aggfunc가 다시 원자료 전체에 적용됨)
    margins_name="Total" # 요약 라벨명
)
print(pivot)  # 결과를 화면에 출력합니다.

```
</details>

In [ ]:
# 여기에 작성하세요
pivot = titanic.pivot_table # 코드를 이어서 완성하세요

## 실전형 분석 문제

여러 전처리와 집계를 조합해 간단한 분석 결과를 만듭니다.


### 문제 1. 성별과 생존율 관계 분석 (Titanic)
Titanic 데이터에서 성별(`Sex`)에 따른 생존율을 비교하세요.  
- 각 성별 그룹별 생존율을 계산하세요.  
- 결과를 DataFrame 형태(`sex`, `survival_rate`)로 출력하세요.  
- 어떤 성별이 더 높은 생존율을 보였는지도 분석해 보세요.

<details><summary>정답</summary>

```python
# 풀이 흐름: 그래프로 확인할 값을 먼저 계산합니다.
# 마지막에 그래프나 표로 결과를 확인합니다.

# 성별별 생존율 계산
survival_by_sex = titanic.groupby("Sex")["Survived"].mean().reset_index()  # 그룹별로 데이터를 묶습니다.
survival_by_sex.columns = ["sex", "survival_rate"]  # 그래프용 열 이름으로 바꿉니다.

print(survival_by_sex)  # 결과를 화면에 출력합니다.

# 분석: female의 생존율이 훨씬 높음

```

</details>

In [ ]:
# 여기에 작성하세요


### 문제 2. 객실 등급과 나이의 관계 (Titanic)
Titanic 데이터에서 객실 등급(`Pclass`)별 승객의 평균 나이를 구하세요.  
- 결측치는 제외하고 계산하세요.  
- 결과를 `pclass`, `mean_age` 형태로 출력하세요.  
- 결과를 보고, 등급별 나이에 어떤 경향이 있는지 해석해 보세요.

<details><summary>정답</summary>

```python
# 풀이 흐름: 그래프로 확인할 값을 먼저 계산합니다.
# 마지막에 그래프나 표로 결과를 확인합니다.

# 결측치 제외 후 평균 나이 계산
age_by_class = titanic.groupby("Pclass")["Age"].mean().reset_index()  # 그룹별로 데이터를 묶습니다.
age_by_class.columns = ["pclass", "mean_age"]  # 그래프용 열 이름으로 바꿉니다.

print(age_by_class)  # 결과를 화면에 출력합니다.

# 분석: 보통 상위 등급(Pclass=1)이 평균 나이가 높음

```

</details>

In [ ]:
# 여기에 작성하세요


### 문제 3. 요일별 자전거 대여량 패턴 (Bike Sharing)
Bike Sharing 데이터에서 날짜(`datetime`)를 기준으로 요일별(`weekday`) 평균 대여량(`count`)을 구하세요.  
- 요일은 0=월요일, 6=일요일입니다.  
- 결과를 요일 오름차순으로 출력하세요.  
- 가장 대여량이 많은 요일과 적은 요일을 분석하세요.

<details><summary>정답</summary>

```python
# 풀이 흐름: 그래프로 확인할 값을 먼저 계산합니다.
# 마지막에 그래프나 표로 결과를 확인합니다.

# 요일별 평균 대여량
bike['weekday'] = pd.to_datetime(bike['datetime']).dt.weekday  # 문자열 날짜를 datetime으로 바꿉니다.

cnt_by_weekday = bike.groupby("weekday")["count"].mean().reset_index()  # 그룹별로 데이터를 묶습니다.

print(cnt_by_weekday)  # 결과를 화면에 출력합니다.

# 분석: 주말(토/일)보다 평일 특정 요일(예: 목/금)에 더 많을 수도 있음

```

</details>

In [ ]:
# 여기에 작성하세요


### 문제 4. 날씨가 대여량에 미치는 영향 (Bike Sharing)
Bike Sharing 데이터에서 날씨 상황(`weather`)에 따라 평균 대여량(`count`)을 구하세요.  
- `weather`: 1=맑음, 2=흐림, 3=비/눈, 4=심각한 날씨로 가정
- 평균 대여량 차이를 막대그래프로 시각화하세요.  
- 날씨가 자전거 대여량에 미치는 영향에 대해 해석해 보세요.

<details><summary>정답</summary>

```python
# 풀이 흐름: 그래프로 확인할 값을 먼저 계산합니다.
# 마지막에 그래프나 표로 결과를 확인합니다.

import matplotlib.pyplot as plt  # 그래프를 그리기 위한 Matplotlib입니다.

count_by_weather = bike.groupby("weather")["count"].mean().reset_index()  # 그룹별로 데이터를 묶습니다.

# 시각화
plt.bar(count_by_weather["weather"], count_by_weather["count"])  # 막대그래프를 그립니다.
plt.xlabel("Weather Situation")  # x축 이름을 설정합니다.
plt.ylabel("Average Rentals")  # y축 이름을 설정합니다.
plt.title("Bike Rentals by Weather")  # 그래프 제목을 설정합니다.
plt.show()  # 그래프를 화면에 표시합니다.

# 분석: 맑을 때 대여량이 가장 많고, 나쁠수록 급감

```

</details>

In [ ]:
# 여기에 작성하세요


### 문제 5. 다중 조건 분석 - 생존율 & 나이 (Titanic)
Titanic 데이터에서 승객을 두 그룹으로 나눠서 생존율을 비교하세요.  
- 그룹 1: 18세 이하 승객 (Children)  
- 그룹 2: 18세 초과 승객 (Adults)  
- 각 그룹을 성별(`Sex`)까지 나눠서 생존율을 계산하세요.  
- 결과를 `group`, `sex`, `survival_rate` 형태로 출력하고, 어떤 그룹이 가장 높은 생존율을 보이는지 해석하세요.

<details><summary>정답</summary>

```python
# 풀이 흐름: 그래프로 확인할 값을 먼저 계산합니다.
# 마지막에 그래프나 표로 결과를 확인합니다.

# 나이 그룹 컬럼 생성
titanic["AgeGroup"] = titanic["Age"].apply(  # 함수를 각 값에 적용합니다.
    lambda x: "Child" if x <= 18 else "Adult"
)

# 그룹별 + 성별 생존율
survival = titanic.groupby(["AgeGroup", "Sex"])["Survived"].mean().reset_index()  # 그룹별로 데이터를 묶습니다.
survival.columns = ["group", "sex", "survival_rate"]  # 그래프용 열 이름으로 바꿉니다.

print(survival)  # 결과를 화면에 출력합니다.

# 분석: female Adult의 생존율이 가장 높음

```

</details>

In [ ]:
# 여기에 작성하세요
